### ISSUE TITLE
Different file size issue

### ISSUE THREAD

**Issue by leogouttefarde** [fbeaudet/ips.py#1]
When creating a patch for a file & the file size changes, the following error occurs :
```
Traceback (most recent call last):
  File "./ips.py", line 371, in <module>
    main()
  File "./ips.py", line 360, in main
    taskResult = createPatch(sys.argv[2], sys.argv[3], sys.argv[4])
  File "./ips.py", line 194, in createPatch
    offset[x] = a >> (16 - x * 8)
ValueError: byte must be in range(0, 256)
```

**Comment by fbeaudet** [comment]
Hi!
I'm gonna try reproduce this today, thanks for the issue!

**Comment by fbeaudet** [comment]
Couldn't reproduce it by simply changing my file sizes.
If that's possible for you, I'd appreciate if you could send me the files that were causing the bug.

Make sure it is safe with the IPS spec (old format):
- IPS files can patch every file not larger than 2^24-1 bits (2047 Mb)
- Every patch should not be larger than 2^16-1 bits (7.99 Mb)

**Comment by leogouttefarde** [comment]
Ok indeed it doesn't seem to occur all the time. Herewith some [samples](https://github.com/fbeaudet/ips.py/files/1366478/samples.zip)

```
python3 ./ips.py create original final pp
Traceback (most recent call last):
  File "./ips.py", line 371, in <module>
    main()
  File "./ips.py", line 360, in main
    taskResult = createPatch(sys.argv[2], sys.argv[3], sys.argv[4])
  File "./ips.py", line 194, in createPatch
    offset[x] = a >> (16 - x * 8)
ValueError: byte must be in range(0, 256)
```

**Comment by leogouttefarde** [comment]
Looked into it. You probably need to write something like this on line 194 :
```
offset[x] = (a >> (16 - x * 8)) % 256
```

**Comment by fbeaudet** [comment]
Thanks!!

**Comment by Zuccace** [comment]
I installed this as system wide (with a small patch that adds shebang for python3).
I tested with two random data files, each 2048 bytes long exactly.
```
zucca@wren /tmp/lipx $ ips-tool create 2048b_1.rand 2048b_2.rand rand.ips
Traceback (most recent call last):
  File "/usr/bin/ips-tool", line 373, in <module>
    main()
  File "/usr/bin/ips-tool", line 362, in main
    taskResult = createPatch(sys.argv[2], sys.argv[3], sys.argv[4])
  File "/usr/bin/ips-tool", line 234, in createPatch
    size[x] = len(record) >> (8 - x * 8)
ValueError: byte must be in range(0, 256)
```
So it seems to happen even if old and new files have the same size.

**Comment by Zuccace** [comment]
I think "I" fixed the issue. Here's [my patch](https://raw.githubusercontent.com/Zuccace/zucca-overlay/956bf338784d9881b4e14873761693e7b3dc07a6/dev-util/fbeaudet-ips-tool/files/0.1_alpha-r1.patch). Note that it contains other changes too, so do change them as you see fit if you choose to use it. ;) For the _actual fix_ you can thank [kylon](https://github.com/kylon).
Please test well, as I'm not familiar with IPS file format (and I'm not a python programmer either).

**Comment by fbeaudet** [comment]
Thanks! Doing a modulo 256 definitely caps the value, but it's returning a remainder... I have to get back into this, been years.
